### ISSUE TITLE
[1.19.2] ticking entity mixin crash due to ImprovedCrossbowGoal

### ISSUE THREAD

**Issue by LordDecay26** [team-abnormals/savage-and-ravage#120]
problematic line in the latest.log:
`net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot read field "f_82479_" because "p_151363_" is null
	at net.minecraft.world.level.BlockGetter.m_151361_(BlockGetter.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.level.BlockGetter.m_45547_(BlockGetter.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at com.teamabnormals.savage_and_ravage.common.entity.ai.goal.ImprovedCrossbowGoal.canSeeTargetBlock(ImprovedCrossbowGoal.java:252) ~[savage_and_ravage-1.19-5.0.2.jar%23264!/:5.0.2]
	at com.teamabnormals.savage_and_ravage.common.entity.ai.goal.ImprovedCrossbowGoal.m_8037_(ImprovedCrossbowGoal.java:137) ~[savage_and_ravage-1.19-5.0.2.jar%23264!/:5.0.2]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:712) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:504) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.raid.Raider.m_8107_(Raider.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23308!/:?]`
	
crashlog:
https://pastebin.com/Fvgw1NLw

**Comment by ZilverLazarus** [comment]
I can also confirm that when this bug doesn't cause a crash, it takes a heavy toll on integrated server performance according to Spark.
[https://spark.lucko.me/9Ckf0TXuub](url)
[https://imgur.com/ixpD6hw](url)
